"""
clasp/cli/cmd_init.py

`clasp init`

Interactive first-time setup wizard.

Creates ~/.clasp/config.yaml with sane defaults by asking the user:
  1. Which providers they want to enable
  2. API key(s) for each selected provider
  3. Proxy port   (default 8082)
  4. Proxy API key (default "freecc")

Then offers to auto-launch `clasp server`.

If config.yaml already exists, asks the user whether to overwrite.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import Optional

import typer

# ── provider catalogue (subset — enough for the wizard) ─────────────────────

PROVIDERS: list[dict] = [
    {
        "name":  "nvidia_nim",
        "label": "NVIDIA NIM",
        "note":  "40 RPM free • build.nvidia.com",
        "key_hint": "nvapi-...",
        "multi_key": True,
    },
    {
        "name":  "gemini",
        "label": "Google Gemini AI Studio",
        "note":  "15 RPM free • 1M tokens/day • aistudio.google.com",
        "key_hint": "AIza...",
        "multi_key": True,
    },
    {
        "name":  "cerebras",
        "label": "Cerebras",
        "note":  "30 RPM free • Ultra-fast inference • inference.cerebras.ai",
        "key_hint": "csk-...",
        "multi_key": False,
    },
    {
        "name":  "groq",
        "label": "Groq",
        "note":  "30 RPM free • console.groq.com",
        "key_hint": "gsk_...",
        "multi_key": False,
    },
    {
        "name":  "fireworks",
        "label": "Fireworks AI",
        "note":  "Free credits on signup • fireworks.ai",
        "key_hint": "fw-...",
        "multi_key": False,
    },
    {
        "name":  "openrouter",
        "label": "OpenRouter",
        "note":  "Free models with :free suffix • openrouter.ai",
        "key_hint": "sk-or-...",
        "multi_key": True,
    },
    {
        "name":  "mistral",
        "label": "Mistral AI",
        "note":  "Free experiment plan • console.mistral.ai",
        "key_hint": "...",
        "multi_key": False,
    },
    {
        "name":  "together",
        "label": "together.ai",
        "note":  "Free credits on signup • together.ai",
        "key_hint": "...",
        "multi_key": False,
    },
    {
        "name":  "ollama",
        "label": "Ollama (local)",
        "note":  "Unlimited • runs on your machine • no API key needed",
        "key_hint": None,
        "multi_key": False,
    },
    {
        "name":  "lm_studio",
        "label": "LM Studio (local)",
        "note":  "Unlimited • runs on your machine • no API key needed",
        "key_hint": None,
        "multi_key": False,
    },
]

CLASP_DIR = Path.home() / ".clasp"
CONFIG_PATH = CLASP_DIR / "config.yaml"

# ── YAML writer (no ruamel dependency for the wizard) ────────────────────────

def _write_yaml(cfg: dict) -> str:
    """
    Minimal YAML serialiser sufficient for the config schema.
    Keys are written in a human-friendly order; string values are quoted.
    Falls back to ruamel.yaml if available for proper formatting.
    """
    try:
        from ruamel.yaml import YAML  # type: ignore[import]
        import io
        y = YAML()
        y.default_flow_style = False
        buf = io.StringIO()
        y.dump(cfg, buf)
        return buf.getvalue()
    except ImportError:
        pass

    # Pure-Python fallback — generates valid YAML for our schema
    lines: list[str] = [
        "# CLASP Configuration — generated by clasp init",
        "",
    ]

    def _emit(obj: object, indent: int = 0) -> None:
        pad = "  " * indent
        if isinstance(obj, dict):
            for k, v in obj.items():
                if isinstance(v, dict):
                    lines.append(f"{pad}{k}:")
                    _emit(v, indent + 1)
                elif isinstance(v, list):
                    lines.append(f"{pad}{k}:")
                    for item in v:
                        if isinstance(item, str):
                            lines.append(f'{pad}  - "{item}"')
                        else:
                            lines.append(f"{pad}  - {item}")
                elif isinstance(v, str):
                    lines.append(f'{pad}{k}: "{v}"')
                elif isinstance(v, bool):
                    lines.append(f'{pad}{k}: {"true" if v else "false"}')
                elif v is None:
                    lines.append(f"{pad}{k}: null")
                else:
                    lines.append(f"{pad}{k}: {v}")

    _emit(cfg)
    return "\n".join(lines) + "\n"


# ── config builder ────────────────────────────────────────────────────────────

def _build_config(
    enabled_providers: list[dict],
    port: int,
    api_key: str,
) -> dict:
    """Assemble the full config dict from wizard answers."""

    provider_chain = [p["name"] for p in enabled_providers]

    # Determine default model routing from enabled providers (first = primary)
    primary = provider_chain[0] if provider_chain else "nvidia_nim"

    # Smart defaults: prefer NIM for compute, Gemini for long context
    nim_enabled  = any(p["name"] == "nvidia_nim" for p in enabled_providers)
    gem_enabled  = any(p["name"] == "gemini"     for p in enabled_providers)
    cer_enabled  = any(p["name"] == "cerebras"   for p in enabled_providers)
    grq_enabled  = any(p["name"] == "groq"       for p in enabled_providers)

    def _default(candidates: list[str]) -> str:
        for c in candidates:
            if any(p["name"] == c for p in enabled_providers):
                return c
        return primary

    opus_prov    = _default(["nvidia_nim", "openrouter", "gemini"])
    sonnet_prov  = _default(["nvidia_nim", "gemini", "cerebras"])
    haiku_prov   = _default(["cerebras", "groq", "nvidia_nim"])
    fable_prov   = _default(["gemini", "nvidia_nim"])
    think_prov   = _default(["nvidia_nim", "gemini"])
    long_prov    = _default(["gemini", "openrouter", "nvidia_nim"])
    bg_prov      = _default(["groq", "cerebras", "nvidia_nim"])

    # All disabled providers still appear in the config (turned off)
    enabled_names = {p["name"] for p in enabled_providers}
    provider_section: dict = {}

    for prov in PROVIDERS:
        name = prov["name"]
        keys_list = prov.get("_keys", [])
        entry: dict = {"enabled": name in enabled_names}
        if name in ("ollama", "lm_studio"):
            entry["base_url"] = (
                "http://localhost:11434" if name == "ollama" else "http://localhost:1234"
            )
        else:
            entry["keys"] = keys_list
        provider_section[name] = entry

    return {
        "server": {
            "host": "127.0.0.1",
            "port": port,
            "api_key": api_key,
            "request_timeout_seconds": 300,
            "max_queue_depth": 50,
            "max_queue_wait_seconds": 180,
            "log_level": "INFO",
            "live_tui": False,
        },
        "routing": {
            "strategy": "priority-chain",
            "models": {
                "opus":    f"{opus_prov}/nvidia/llama-3.1-nemotron-70b-instruct",
                "sonnet":  f"{sonnet_prov}/nvidia/llama-3.1-nemotron-70b-instruct",
                "haiku":   f"{haiku_prov}/llama3.1-8b",
                "fable":   f"{fable_prov}/models/gemini-2.5-flash",
                "default": f"{primary}/nvidia/llama-3.1-nemotron-70b-instruct",
            },
            "by_type": {
                "think":        f"{think_prov}/moonshotai/kimi-k2-thinking",
                "long_context": f"{long_prov}/models/gemini-2.5-flash",
                "background":   f"{bg_prov}/llama-3.3-70b-versatile",
                "vision":       "openrouter/google/gemini-2.5-flash-preview:free",
            },
        },
        "provider_chain": provider_chain,
        "providers": provider_section,
        "cache": {
            "enabled": True,
            "memory_max_entries": 500,
            "sqlite_ttl_seconds": 300,
            "sqlite_path": "~/.clasp/cache.db",
        },
        "optimizer": {
            "local_probe_answering": True,
            "system_prompt_dedup": True,
            "context_pruning": {
                "enabled": True,
                "strategy": "keep_edges",
                "keep_first": 3,
                "keep_last": 10,
            },
        },
        "shared_pool": {
            "enabled": False,
            "auth_tokens": [],
            "per_user_rpm_limit": 20,
        },
    }


# ── command ──────────────────────────────────────────────────────────────────

def init_cmd() -> None:
    """Interactive first-time setup wizard. Creates ~/.clasp/config.yaml."""

    typer.echo("")
    typer.echo("  ◆ CLASP — First-time Setup Wizard")
    typer.echo("  ────────────────────────────────────")
    typer.echo("  Configure providers and API keys to get started.")
    typer.echo("  (Press Ctrl+C at any time to cancel)\n")

    # ── check for existing config ─────────────────────────────────────────────
    if CONFIG_PATH.exists():
        overwrite = typer.confirm(
            f"  Config already exists at {CONFIG_PATH}. Overwrite?",
            default=False,
        )
        if not overwrite:
            typer.echo("  Aborted — existing config kept.")
            raise typer.Exit(0)
        typer.echo("")

    # ── provider selection ────────────────────────────────────────────────────
    typer.echo("  Step 1 — Choose providers to enable")
    typer.echo("  (You can add more later via `clasp server` UI)\n")

    for i, prov in enumerate(PROVIDERS, start=1):
        default_enable = prov["name"] in ("nvidia_nim", "gemini", "cerebras", "groq")
        enable = typer.confirm(
            f"  [{i:2d}] {prov['label']}\n       {prov['note']}\n       Enable?",
            default=default_enable,
        )
        prov["_enabled"] = enable
        typer.echo("")

    enabled = [p for p in PROVIDERS if p.get("_enabled")]

    if not enabled:
        typer.echo("  ⚠ No providers selected. You can configure them later in the UI.")
        typer.echo("    Add at least one provider API key to start routing requests.\n")

    # ── API keys ──────────────────────────────────────────────────────────────
    typer.echo("  Step 2 — Enter API keys for enabled providers\n")

    for prov in enabled:
        name  = prov["name"]
        label = prov["label"]
        hint  = prov.get("key_hint")

        # Local providers don't need keys
        if hint is None:
            typer.echo(f"  {label}: no API key required (local model server)\n")
            prov["_keys"] = []
            continue

        keys: list[str] = []
        prompt_label = f"  {label} API key{' (blank to skip)' if not keys else ' (blank to finish)'}"

        while True:
            key = typer.prompt(prompt_label, default="", hide_input=True, show_default=False)
            key = key.strip()
            if not key:
                if not keys:
                    typer.echo(f"    ⚠ No key added for {label}. You can add one later in the UI.\n")
                break
            keys.append(key)
            typer.echo(f"    ✓ Key added ({key[:6]}{'*' * max(0, len(key)-10)}{key[-4:] if len(key) > 10 else ''})")
            if not prov["multi_key"]:
                typer.echo("")
                break
            typer.echo(f"    (Add another key for extra quota, or leave blank to continue)")

        prov["_keys"] = keys

    # ── server settings ───────────────────────────────────────────────────────
    typer.echo("  Step 3 — Server settings\n")

    port = typer.prompt("  Proxy port", default=8082, type=int)
    api_key = typer.prompt(
        "  Proxy API key (what Claude Code sends as Bearer token)",
        default="freecc",
    )
    typer.echo("")

    # ── write config ──────────────────────────────────────────────────────────
    cfg = _build_config(enabled, port, api_key)

    # Inject the real keys into the config dict
    for prov in PROVIDERS:
        name = prov["name"]
        keys = prov.get("_keys", [])
        if name in cfg["providers"] and "keys" in cfg["providers"][name]:
            cfg["providers"][name]["keys"] = keys

    CLASP_DIR.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(_write_yaml(cfg))

    typer.echo(f"  ✓ Config written to {CONFIG_PATH}")
    typer.echo(f"  ✓ {len(enabled)} provider(s) enabled: "
               f"{', '.join(p['label'] for p in enabled) or 'none'}\n")

    # ── launch server? ────────────────────────────────────────────────────────
    launch = typer.confirm("  Launch `clasp server` now?", default=True)
    if launch:
        typer.echo("")
        typer.echo("  Starting CLASP server...\n")
        try:
            # Replace current process with clasp server so the user sees live output
            import os, shutil
            clasp_bin = shutil.which("clasp") or sys.executable
            if shutil.which("clasp"):
                os.execvp("clasp", ["clasp", "server"])
            else:
                # Fall back to python -m clasp server
                os.execvp(sys.executable, [sys.executable, "-m", "clasp", "server"])
        except Exception as e:
            typer.echo(f"  ✗ Could not launch server: {e}", err=True)
            typer.echo("    Run it manually: clasp server")
            raise typer.Exit(1)
    else:
        typer.echo("  When you're ready, run:\n")
        typer.echo("    clasp server     # Start proxy + open config UI")
        typer.echo("    clasp claude     # Launch Claude Code through the proxy")
        typer.echo("")